# Generated by Django 5.2.1 on 2025-07-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_propertyimage_options_propertyimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order', '-is_primary', 'id']},
        ),
    ]
