# Generated by Django 5.2.1 on 2025-09-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_propertyimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('land', 'Land'), ('temporal', 'Temporal'), ('vacacional', 'Vacacional'), ('tradicional', 'Tradicional')], max_length=20),
        ),
    ]
