# Generated by Django 5.2.1 on 2025-10-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='s3_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
